/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "MyShopPurchaseOrders"
 * 	found in "productExample1.asn"
 */

#ifndef	_Address_H_
#define	_Address_H_


#include <asn_application.h>

/* Including external dependencies */
#include <VisibleString.h>
#include <NumericString.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Address */
typedef struct Address {
	VisibleString_t	*street	/* OPTIONAL */;
	VisibleString_t	 city;
	VisibleString_t	 state;
	NumericString_t	 zipCode;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Address_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Address;

#ifdef __cplusplus
}
#endif

#endif	/* _Address_H_ */
#include <asn_internal.h>
