/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "MyShopPurchaseOrders"
 * 	found in "productExample1.asn"
 */

#ifndef	_DATE_H_
#define	_DATE_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NULL.h>

#ifdef __cplusplus
extern "C" {
#endif

/* DATE */
typedef NULL_t	 DATE_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DATE;
asn_struct_free_f DATE_free;
asn_struct_print_f DATE_print;
asn_constr_check_f DATE_constraint;
ber_type_decoder_f DATE_decode_ber;
der_type_encoder_f DATE_encode_der;
xer_type_decoder_f DATE_decode_xer;
xer_type_encoder_f DATE_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _DATE_H_ */
#include <asn_internal.h>
