/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "COMPOSITESIGALGS"
 * 	found in "pqASN1_compiling.asn"
 */

#ifndef	_ECParameters_H_
#define	_ECParameters_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>
#include <NativeInteger.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ECParameters */
typedef struct ECParameters {
	OCTET_STRING_t	 a;
	OCTET_STRING_t	 b;
	OCTET_STRING_t	 p;
	long	 n;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ECParameters_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ECParameters;

#ifdef __cplusplus
}
#endif

#endif	/* _ECParameters_H_ */
#include <asn_internal.h>
