/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "COMPOSITESIGALGS"
 * 	found in "pqASN1_compiling.asn"
 */

#include "ExplicitCompositeSignatureParams.h"

static int
memb_firstAlgorithmParams_constraint_1(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	
	if(1 /* No applicable constraints whatsoever */) {
		/* Nothing is here. See below */
	}
	
	return td->check_constraints(td, sptr, ctfailcb, app_key);
}

static int
memb_secondAlgorithmParams_constraint_1(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	
	if(1 /* No applicable constraints whatsoever */) {
		/* Nothing is here. See below */
	}
	
	return td->check_constraints(td, sptr, ctfailcb, app_key);
}

static asn_TYPE_member_t asn_MBR_ExplicitCompositeSignatureParams_1[] = {
	{ ATF_OPEN_TYPE | ATF_NOFLAGS, 0, offsetof(struct ExplicitCompositeSignatureParams, firstAlgorithmParams),
		-1 /* Ambiguous tag (ANY?) */,
		0,
		&asn_DEF_ANY,
		memb_firstAlgorithmParams_constraint_1,
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"firstAlgorithmParams"
		},
	{ ATF_OPEN_TYPE | ATF_NOFLAGS, 0, offsetof(struct ExplicitCompositeSignatureParams, secondAlgorithmParams),
		-1 /* Ambiguous tag (ANY?) */,
		0,
		&asn_DEF_ANY,
		memb_secondAlgorithmParams_constraint_1,
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"secondAlgorithmParams"
		},
};
static const ber_tlv_tag_t asn_DEF_ExplicitCompositeSignatureParams_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SEQUENCE_specifics_t asn_SPC_ExplicitCompositeSignatureParams_specs_1 = {
	sizeof(struct ExplicitCompositeSignatureParams),
	offsetof(struct ExplicitCompositeSignatureParams, _asn_ctx),
	0,	/* No top level tags */
	0,	/* No tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_ExplicitCompositeSignatureParams = {
	"ExplicitCompositeSignatureParams",
	"ExplicitCompositeSignatureParams",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_ExplicitCompositeSignatureParams_tags_1,
	sizeof(asn_DEF_ExplicitCompositeSignatureParams_tags_1)
		/sizeof(asn_DEF_ExplicitCompositeSignatureParams_tags_1[0]), /* 1 */
	asn_DEF_ExplicitCompositeSignatureParams_tags_1,	/* Same as above */
	sizeof(asn_DEF_ExplicitCompositeSignatureParams_tags_1)
		/sizeof(asn_DEF_ExplicitCompositeSignatureParams_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_ExplicitCompositeSignatureParams_1,
	2,	/* Elements count */
	&asn_SPC_ExplicitCompositeSignatureParams_specs_1	/* Additional specs */
};

