/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "COMPOSITESIGALGS"
 * 	found in "pqASN1_compiling.asn"
 */

#ifndef	_ExplicitCompositeSignatureValue_H_
#define	_ExplicitCompositeSignatureValue_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ExplicitCompositeSignatureValue */
typedef struct ExplicitCompositeSignatureValue {
	OCTET_STRING_t	 firstSignatureValue;
	OCTET_STRING_t	 secondSignatureValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ExplicitCompositeSignatureValue_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ExplicitCompositeSignatureValue;

#ifdef __cplusplus
}
#endif

#endif	/* _ExplicitCompositeSignatureValue_H_ */
#include <asn_internal.h>
