/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "MyShopPurchaseOrders"
 * 	found in "productExample1.asn"
 */

#ifndef	_Item_H_
#define	_Item_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <VisibleString.h>
#include <NativeReal.h>
#include <BOOLEAN.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Item */
typedef struct Item {
	long	 itemCode;
	VisibleString_t	 color;
	long	 power;
	long	 deliveryTime;
	long	 quantity;
	double	 unitPrice;
	BOOLEAN_t	 isTaxable;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Item_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Item;

#ifdef __cplusplus
}
#endif

#endif	/* _Item_H_ */
#include <asn_internal.h>
