/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "MyShopPurchaseOrders"
 * 	found in "productExample1.asn"
 */

#ifndef	_ListOfItems_H_
#define	_ListOfItems_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct Item;

/* ListOfItems */
typedef struct ListOfItems {
	A_SEQUENCE_OF(struct Item) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ListOfItems_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ListOfItems;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "Item.h"

#endif	/* _ListOfItems_H_ */
#include <asn_internal.h>
