/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "MyShopPurchaseOrders"
 * 	found in "productExample1.asn"
 */

#ifndef	_PurchaseOrder_H_
#define	_PurchaseOrder_H_


#include <asn_application.h>

/* Including external dependencies */
#include "DATE.h"
#include "CustomerInfo.h"
#include "ListOfItems.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* PurchaseOrder */
typedef struct PurchaseOrder {
	DATE_t	 dateOfOrder;
	CustomerInfo_t	 customer;
	ListOfItems_t	 items;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} PurchaseOrder_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PurchaseOrder;

#ifdef __cplusplus
}
#endif

#endif	/* _PurchaseOrder_H_ */
#include <asn_internal.h>
