/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "COMPOSITESIGALGS"
 * 	found in "pqASN1_compiling.asn"
 */

#ifndef	_RSAParameters_H_
#define	_RSAParameters_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NULL.h>

#ifdef __cplusplus
extern "C" {
#endif

/* RSAParameters */
typedef NULL_t	 RSAParameters_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RSAParameters;
asn_struct_free_f RSAParameters_free;
asn_struct_print_f RSAParameters_print;
asn_constr_check_f RSAParameters_constraint;
ber_type_decoder_f RSAParameters_decode_ber;
der_type_encoder_f RSAParameters_encode_der;
xer_type_decoder_f RSAParameters_decode_xer;
xer_type_encoder_f RSAParameters_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _RSAParameters_H_ */
#include <asn_internal.h>
